### ISSUE TITLE
Error while installing AzureRM Module

### ISSUE THREAD

**Issue by mviveki** [PowerShell/PowerShellGetv2#194] opened 2017-11-11 15:26 UTC
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

```PowerShell

> $PSVersionTable

> Get-Module

> Get-Module -ListAvailable PowerShellGet,PackageManagement

> Get-PackageProvider

> Get-PackageProvider -ListAvailable
```
PS C:\Windows\system32> Install-Module AzureRM

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): a
PackageManagement\Install-Package : Package 'AzureRM.profile' failed to be installed because: The process cannot
access the file 'C:\Users\mviveki\AppData\Local\Temp\moly22ns\Microsoft.Azure.Commands.ResourceManager.Common.dll'
because it is being used by another process.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1375 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (AzureRM.profile:String) [Install-Package], Exception
    + FullyQualifiedErrorId : Package '{0}' failed to be installed because: {1},Microsoft.PowerShell.PackageManagement
   .Cmdlets.InstallPackage

PackageManagement\Install-Package : Collection was modified; enumeration operation may not execute.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1375 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallP
   ackage

**Comment by mviveki** [comment] 2017-11-11 15:28
PS C:\Windows\system32> Install-Module AzureRM

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): a
PackageManagement\Install-Package : Package 'AzureRM.profile' failed to be installed because: The process cannot
access the file 'C:\Users\mviveki\AppData\Local\Temp\moly22ns\Microsoft.Azure.Commands.ResourceManager.Common.dll'
because it is being used by another process.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1375 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (AzureRM.profile:String) [Install-Package], Exception
    + FullyQualifiedErrorId : Package '{0}' failed to be installed because: {1},Microsoft.PowerShell.PackageManagement
   .Cmdlets.InstallPackage

PackageManagement\Install-Package : Collection was modified; enumeration operation may not execute.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1375 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallP
   ackage

**Comment by bmanikm** [comment] 2017-11-11 17:32
This is duplicate of https://github.com/PowerShell/PowerShellGet/issues/178.

Please take a look at the workaround [option](https://github.com/PowerShell/PowerShellGet/issues/178#issuecomment-337690739).

**Closed as completed by bmanikm** 2017-11-11 17:32 UTC
Labels: Issue-Bug

**Comment by mviveki** [comment] 2017-11-11 18:52
Tried to save the module, but the same error.
Save-Module AzureRM -Path c:\"Program Files"\WindowsPowerShell\Modules\WARNING: Package 'AzureRM.profile' failed to be installed because: The process cannot access the file'C:\Users\mviveki\AppData\Local\Temp\lj0ljfh4\Microsoft.Azure.Commands.Common.Authentication.Abstractions.dll' becauseit is being used by another process.WARNING: Dependent Package 'AzureRM.prof ========== Mahesh Dutt
