### ISSUE TITLE
Publish-Script and Publish-Module don't accept proxy parameter

### ISSUE THREAD

**Issue by dlip** [PowerShell/PowerShellGetv2#225] opened 2018-01-24 04:47 UTC
Publish-Script and Publish-Module don't accept proxy parameter to pass onto Install-NuGetClientBinaries so the command fails behind corporate proxy

## Expected Behavior
Can use proxy with functions that depend on nuget

## Current Behavior
Can't pass proxy

## Possible Solution
Add parameters to these functions

**Comment by VerdonTrigance** [comment] 2018-04-10 08:37
Agree

**Comment by SydneyhSmith** [comment] 2018-10-22 22:11
@dlip could you please post the steps to reproduce so that we can better understand what is causing this issue?

**Comment by SydneyhSmith** [comment] 2019-02-28 18:28
Closing as in-active will re-open if this is still an issue

**Closed as completed by SydneyhSmith** 2019-02-28 18:28 UTC
Labels: Issue-Bug, Up-For-Grabs, good first issue, Review, Publish-Module

**Comment by Stephanevg** [comment] 2020-02-03 17:12
Hi @SydneyhSmith 
I would recommend we reopen this one. This was not a bug, but simply a comment saying that it is not possible to transmit proxy settings when publishing a module since the cmdlet doesn't has the -Proxy parameter.
I face the same limitation today, I think adding this one in the design of powershellGet 3.0 would make sense.

**Comment by bateskevin** [comment] 2020-02-06 16:13
Please reopen this! This is definitly still an issue.
