### ISSUE TITLE
Install-module do not install PSScriptAnalyzer

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/PowerShellGetv2#15] opened 2016-10-15 18:08 UTC
It try to update PSscriptAnalyzer module v1.8.1,  but without success. 
I have removed the folder (1.8.0) and try install-module :
![pssa-seven](https://cloud.githubusercontent.com/assets/4894452/19412257/5eb6eff4-9312-11e6-8e95-483a9c79d798.png)
No errror, but no module is installed.
I must use the _-SkipPublisherCheck_ parameter.

Update-module works on Windows server 2012 :
![pssa-srv2012](https://cloud.githubusercontent.com/assets/4894452/19412284/bb7117ce-9312-11e6-856f-a1604087a04e.png)

PS v5.0

**Comment by PlagueHO** [comment] 2016-10-15 22:23
Hi @LaurentDardenne - I think this is expected/intended behavior.

It is documented in [this blog post](https://blogs.msdn.microsoft.com/powershell/2016/09/29/powershellget-and-packagemanagement-in-powershell-gallery-and-github/) from the PowerShell Team. See the **Important Note** at the bottom of the post. HTH!

**Comment by bmanikm** [comment] 2016-10-15 23:25
@LaurentDardenne This is a known issue (#8) and got fixed in [1.1.1.0](https://www.powershellgallery.com/packages/powershellget/1.1.1.0) version of PowerShellGet. Please try again after installing the latest version of PowerShellGet as documented in [this blog post](https://blogs.msdn.microsoft.com/powershell/2016/09/29/powershellget-and-packagemanagement-in-powershell-gallery-and-github/).

**Closed as completed** 2016-10-17 07:42 UTC
