### ISSUE TITLE
Publish-Module does not correctly check versions

### ISSUE THREAD

**Issue by Skons** [PowerShell/PowerShellGetv2#262] opened 2018-04-18 19:57 UTC
On line 560 in Publish-Module.ps1 there is this bit of code
elseif (-not $Force -and ($currentPSGetItemPrereleaseString -gt $moduleInfoPrerelease))

This does not allow a upgrade like 1.0.9 to 1.0.10 because they are compared as strings. I think the line of code should be
elseif (-not $Force -and ([version]$currentPSGetItemPrereleaseString -gt [version]$moduleInfoPrerelease))

![image](https://user-images.githubusercontent.com/13225002/38954982-88637938-4353-11e8-94a2-d5e701ab1eff.png)

**Comment by bmanikm** [comment] 2018-04-18 20:25
@Skons `($currentPSGetItemPrereleaseString -gt $moduleInfoPrerelease)` is comparing the prerelease string values only. I am unable to reproduce the reported error. Can you please provide the debug output along with the [steps](https://github.com/PowerShell/PowerShellGet/issues/new) for reproducing the reported error.

**Comment by Skons** [comment] 2018-04-18 20:46
Ah right, well, my mistake. I was trying to refer to this bit of code, at which i failed miserably. That piece of code is now available in the 1.6.0 version that is published to the powershellgallery. And i can seem to find it in your code.

Do you still want my debug code?


elseif(-not $Force -and ($currentPSGetItemVersion -gt $moduleInfoVersion))
                {
                    $message = $LocalizedData.ModuleVersionShouldBeGreaterThanGalleryVersion -f ($moduleInfo.Name, $moduleInfoVersion, $currentPSGetItemFullVersion, $currentPSGetItemInfo.RepositorySourceLocation)
                    ThrowError -ExceptionName "System.InvalidOperationException" `
                               -ExceptionMessage $message `
                               -ErrorId "ModuleVersionShouldBeGreaterThanGalleryVersion" `
                               -CallerPSCmdlet $PSCmdlet `
                               -ErrorCategory InvalidOperation
                }

**Comment by bmanikm** [comment] 2018-04-18 21:18
Thanks @Skons! This issue got resolved with PR #219 for issue #217.

**Closed as completed** 2018-05-08 01:16 UTC
Labels: Issue-Bug
