### ISSUE TITLE
Update-ModuleManifest reverts back to previous key value after subsequent calls

### ISSUE THREAD

**Issue by marckassay** [PowerShell/PowerShellGetv2#294] opened 2018-06-27 01:57 UTC
In essence the following below fails.  If the current value of LicenseUri is 'https://github.com/x', the call to update HelpInfoUri seems to revert LicenseUri back to that value.
```powershell
Update-ModuleManifest -Path $ManifestPath -LicenseUri "https://github.com/y"
Update-ModuleManifest -Path $ManifestPath -HelpInfoUri "https://github.com/z"
(Import-PowerShellDataFile -Path $ManifestPath).PrivateData.PSData.LicenseUri | Should -Be "https://github.com/y"
```

This seems to show that #284 needs more changes.  The build of PowerShellGet I'm using is post to d24838fc commit.  See environment output below.

## Expected Behavior

Subsequent calls to update different keys using Update-ModuleManifest _shouldn't_ revert to previous key value.

## Current Behavior

Subsequent calls to update different keys using Update-ModuleManifest reverts to previous key value.

## Steps to Reproduce (for bugs)
```powershell
> git clone https://gist.github.com/e94b3478c453a30c8a021845a84475b7.git
> Invoke-Pester .\e94b3478c453a30c8a021845a84475b7\Update-ModuleManifest.Tests.ps1
Executing all tests in '.\e94b3478c453a30c8a021845a84475b7\Update-ModuleManifest.Tests.ps1'

Executing script .\e94b3478c453a30c8a021845a84475b7\Update-ModuleManifest.Tests.ps1

  Describing Test Update-ModuleManifest

    Context With LicenseUri key ending a value of: MockModule/master/LICENSE
      [+] Should have LicenseUri with a 'master' segment 375ms
      [+] Should update LicenseUri from having a 'master' segment to '3.0.0' segment 113ms
      [-] Should (But Fails to) update LicenseUri from having a '3.0.0' segment to '3.0.1' segment 211ms
        Expected string length 84 but was 85. Strings differ at index 70.
        Expected: {LicenseUri = 'https://raw.githubusercontent.com/marckassay/MockModule/3.0.1/LICENSE'}
        But was:  {LicenseUri = 'https://raw.githubusercontent.com/marckassay/MockModule/master/LICENSE'}
        ---------------------------------------------------------------------------------^
        157:             $Results[100].Trim() | Should -Be "LicenseUri = 'https://raw.githubusercontent.com/marckassay/MockModule/3.0.1/LICENSE'"
        at Invoke-Assertion, C:\Program Files\PowerShell\Modules\Pester\4.1.1\Functions\Assertions\Should.ps1: line 209
        at <ScriptBlock>, E:\temp\e94b3478c453a30c8a021845a84475b7\Update-ModuleManifest.Tests.ps1: line 157
Tests completed in 700ms
Tests Passed: 2, Failed: 1, Skipped: 0, Pending: 0, Inconclusive: 0
```

## Your Environment

```PowerShell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0
PSEdition                      Core
GitCommitId                    v6.0.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

> Get-Module
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     1.0.0.0    CimCmdlets                          {Get-CimAssociatedInstance, Get-CimClass, Get-CimInstance, Get-CimSession, Invoke-CimMethod, New-CimInstance, New-CimSession, New-CimSe...
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty, Convert-Path, Copy-Item, Copy-ItemProperty, Debug-Process, Get-ChildItem, ...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object, ConvertFrom-Csv, ConvertFrom-Json, ConvertFrom-StringData, ConvertTo-Csv, Conver...
Script     0.0.2      MK.PowerShell.Flow                  {Add-ModuleToProfile, Backup-Sources, Build-Documentation, Build-PlatyPSMarkdown, ConvertTo-EnumFlag, Export-History, Get-LatestError, ...
Script     1.1.7.2    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-PackageProvider, Get-PackageSource, Import-PackageProvider, Install-Package, Inst...
Script     4.1.1      Pester                              {Add-AssertionOperator, AfterAll, AfterEach, AfterEachFeature, AfterEachScenario, Assert-MockCalled, Assert-VerifiableMock, Assert-Veri...
Script     1.1.4      Plaster                             {Get-PlasterTemplate, Invoke-Plaster, New-PlasterManifest, Test-PlasterManifest}
Script     0.9.0      platyPS                             {Get-HelpPreview, Get-MarkdownMetadata, Merge-MarkdownHelp, New-ExternalHelp, New-ExternalHelpCab, New-MarkdownAboutHelp, New-MarkdownH...
Script     0.7.1      posh-git                            {Add-PoshGitToProfile, Add-SshKey, Enable-GitColors, Get-AliasPattern, Get-GitBranch, Get-GitDirectory, Get-GitStatus, Get-SshAgent, Ge...
Script     1.6.5      PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCapability, Find-Script, Get-InstalledModule, Get-InstalledScript, Get-PSReposit...
Script     2.0.0      PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandler, Set-PSReadLineOption, PSConsole...

> Get-Module -ListAvailable PowerShellGet,PackageManagement
    Directory: C:\Program Files\PowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.1.7.2    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource, Install-Package, Import-PackageProvider, Find-PackageProvider, Inst...

> Get-PackageProvider
Name                     Version          DynamicOptions
----                     -------          --------------
NuGet                    2.8.5.210        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag, Contains, AllowPrereleaseVersions, ConfigFile, SkipValidate

> Get-PackageProvider -ListAvailable
Name                     Version          DynamicOptions
----                     -------          --------------
NuGet                    2.8.5.210        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag, Contains, AllowPrereleaseVersions, ConfigFile, SkipValidate

E:\> (Get-Module PowerShellGet).Path
E:\PowerShellGet\PowerShellGet\PSModule.psm1

E:\PowerShellGet [development ≡]> git log
commit c5af7554cc638d80eb3cec6a979949400ae5b0de
Author: alerickson <aerickso@terpmail.umd.edu>
Date:   Sat Jun 2 00:19:32 2018 -0700

    Modified Update-ModuleManifest so prefix is not added to CmdletsToExport (#285)

    * Modified Update-ModuleManifest so prefix is not added to CmdletsToExport, AliasesToExport, FunctionsToExport

commit d24838fc33d6f230ac9fd775f2252d24230bea9a
Author: alerickson <aerickso@terpmail.umd.edu>
Date:   Tue May 22 15:12:31 2018 -0700

    Modified Update-ModuleManifest so that params will not reset to default values (#284)

    * Modified Update-ModuleManifest so that parameters will not reset to default values

    * Added condition for PS version on test for Update-ModuleManifest

commit 61f8bc5569296d02781c1841507c1c413f3a54fc
Author: Igor <iricigor@gmail.com>
Date:   Tue May 22 02:04:28 2018 +0200
```

**Comment by JustinGrote** [comment] 2018-06-28 19:46
I've also noticed it pretty much butchers PrivateData, doesn't re-expand hashtables for instance Plaster Extensions correctly, etc.

I've been using update-metadata from the BuildHelpers module instead, seems to behave much better.

EDIT:

## Reproduction (1.6.5)
![updatemodulemanifestbug](https://user-images.githubusercontent.com/15258962/42058525-8d8b70e6-7ad5-11e8-9824-acf97afa1d31.gif)

**Comment by marckassay** [comment] 2018-07-06 12:19
I will do this unless someone else has already started on it.

**Comment by bmanikm** [comment] 2018-07-09 19:21
@marckassay Thanks for working on this. I have assigned this to you.

**Comment by marckassay** [comment] 2018-07-11 18:45
@JustinGrote, fyi:

> @JustinGrote comment would require another pull-request. He did mention about an alternative function for Update-ModuleManifest which may be beneficial for updates within PowerShellGet. I noticed for the issue he is having involves PowerShellGet's Get-PrivateData which perhaps can benefit from HashData's ConvertTo-HashString with a few changes.

[source](https://github.com/PowerShell/PowerShellGet/pull/300)

**Closed as completed** 2022-03-01 15:09 UTC
Labels: Issue-Bug, good first issue, ModuleManifest
