### ISSUE TITLE
Publish-Module should not require NuGetApiKey

### ISSUE THREAD

**Issue by jzabroski** [PowerShell/PowerShellGetv2#327] opened 2018-09-14 13:46 UTC
`[-NuGetApiKey <string>]` should not be required. For company's publishing packages to trusted internal feeds, Windows Authentication is probably preferred, as an API Key is effectively shared credentials, anyway (bad design), and there is no way for an internal IT team to make sure the API Key is automatically updated on a schedule to product the fidelity of the key. With Windows Authentication, our build server's publish package step can use a Group Managed Service Account (msa) which keeps the authentication credentials secret and locks down the account's privileges only to that one service.

Here is a quote from ProGet's [API Access and API Keys](https://inedo.com/support/documentation/proget/administration/security/api-keys) docs: 
> The most important property of an API Key is the Key. This is an arbitrary string that acts like a password, so make sure to treat it like one. You can set the key value to anything you'd like, or let ProGet auto-generate a value for you.

Here is the offending code, see line 32, `[ValidateNotNullOrEmpty]`:
https://github.com/PowerShell/PowerShellGet/blob/37f2a3f477213be79104695235c8b3ab5eae6e38/PowerShellGet/public/psgetfunctions/Publish-Module.ps1#L31-L34

**Comment by edyoung** [comment] 2018-11-10 06:15
Duplicate of #143

**Closed as completed by edyoung** 2018-11-10 06:15 UTC
Labels: Issue-Enhancement, Publish-Module
