### ISSUE TITLE
Uninstall-Module - Add new parameter -RemoveDependencies 

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShellGetv2#308] opened 2018-08-07 19:38 UTC
This not a bug but it's been trouble me for some time now.  I've done an Uninstall-Module against the AzureRM.Netcore (in this case), but to find out that I have to manually remove all of its module it has previously installed.

## Expected Behavior

Expected behaviour: To have installed all dependent modules belonging to AzureRM.Netcore.

## Current Behavior

Current Behavior: Module AzureRM.Netcore is removed, but leave all other AzureRM.*.Netcore modules installed.

![powershellget_leavingmodules_2018-08-07_15-30-08](https://user-images.githubusercontent.com/19892435/43797880-d9a6be68-9a56-11e8-9a0e-08c9ad0b60cc.jpg)

## Possible Solution

Create a script to loop thru and uninstall the existing module.

## Steps to Reproduce (for bugs)

1. Install-Module -Name AzureRM.Netcore (it will install dependent modules)
2. Get-Module -Listavailable AzureRM.*Netcore | Select Name  (List all installed modules AzureRM.Netcore) - notice that AzureRM.Netcore is listed.
3. Uninstall-Module -Name AzureRM.Netcore
4. Repeat Step 3 - Notice that only AzureRM.Netcore was removed leaving the others installed.

## Your Environment

```PowerShell

PS [57] > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.4
PSEdition                      Core
GitCommitId                    6.1.0-preview.4
OS                             Microsoft Windows 10.0.17730
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

> Get-Module
S [72] > Get-Module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   6.1.0.0    Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemPropert...
Manifest   6.1.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl...
Manifest   6.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Manifest   6.1.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, En...
Script     1.1.7.0    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-Pack...
Script     1.6.0      PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCap...
Script     2.0.0      PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PS...

> Get-Module -ListAvailable PowerShellGet,PackageManagement
    Directory: C:\program files\powershell\6-preview\Modules


ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Script     1.1.7.0    PackageManagement                   Desk      {Find-Package, Get-Package, Get-PackageProvider,...
Script     1.6.0      PowerShellGet                       Desk      {Install-Module, Find-Module, Save-Module, Updat...

> Get-PackageProvider -ListAvailable
Name                     Version          DynamicOptions
----                     -------          --------------
NuGet                    2.8.5.210        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag...
PowerShellGet            1.6.0.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, ...

```

**Comment by bmanikm** [comment] 2018-08-08 20:50
This is a duplicate of #114.

**Closed as completed by bmanikm** 2018-08-08 20:50 UTC
