### ISSUE TITLE
Install-Script -Scope CurrentUser PATH changes should not require a reboot for new PS processes

### ISSUE THREAD

**Issue by NReilingh** [PowerShell/PowerShellGetv2#81] opened 2016-12-20 20:03 UTC
When running Install-Script with a -Scope of CurrentUser, psget checks to make sure that the user's Documents\WindowsPowerShell\Scripts folder is in the PATH, and if it's not, offers to add it.

## Expected Behavior
Since the user is installing a script with powershellget, they should assume that being prompted about a change to their path enabling them to easily run the script will be permanent and work in future powershell sessions.

## Current Behavior
psget only changes the $env:PATH for the current process. This means the change is effective immediately for the current session, but opening a new powershell window will not have the path change.

## Possible Solution
After Install-Script prompts the user to affirm a change to $env:PATH, it should make a permanent change to the current user's PATH that will persist for future sessions without requiring the user to make this change manually or add something to their $profile.

## Your Environment

```PowerShell

Name                           Value
----                           -----
PSVersion                      5.1.14393.576
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.576
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     1.0.0.1    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}
```

**Comment by bmanikm** [comment] 2016-12-20 23:55
@NReilingh Please take a look at the [Install-Script documentation](https://msdn.microsoft.com/en-us/powershell/gallery/psget/script/psget_install-script) to understand more on the prompt for updating the PATH environment variable.

Please provide more details to consistently repro this issue.
Can you provide the output of following commands from a new PS Console on your machine?

```powershell
del "$env:LOCALAPPDATA\Microsoft\Windows\PowerShell\PowerShellGet\PowerShellGetSettings.xml" -force

[System.Environment]::GetEnvironmentVariable('PATH', [System.EnvironmentVariableTarget]::Process) -split ';'
[System.Environment]::GetEnvironmentVariable('PATH', [System.EnvironmentVariableTarget]::User) -split ';'
[System.Environment]::GetEnvironmentVariable('PATH', [System.EnvironmentVariableTarget]::Machine) -split ';'
$env:PATH -split ';'

Install-Script -Verbose -Debug -Scope CurrentUser -Name $ScriptName

[System.Environment]::GetEnvironmentVariable('PATH', [System.EnvironmentVariableTarget]::Process) -split ';'
[System.Environment]::GetEnvironmentVariable('PATH', [System.EnvironmentVariableTarget]::User) -split ';'
[System.Environment]::GetEnvironmentVariable('PATH', [System.EnvironmentVariableTarget]::Machine) -split ';'
$env:PATH -split ';'

```

**Comment by NReilingh** [comment] 2016-12-21 05:38
@bmanikm Thank you for the tips on reproducing this. I experienced the issue on a different machine earlier today. The machine I'm on now _should_ be on the same versions, but the behavior here is as expected. I'll need to try to reproduce on the first machine tomorrow.

As a side issue, I have noticed that all of the existing PATH settings on my system are of the form `C:\Path\To\Folder;`, with the semicolon coming at the end, but when psget adds the user scripts directory to the path, it _prefixes_ the semicolon, resulting in `C:\My\Existing\Paths;;C:\PowerShellGet\User\Script\Path`. This smells like it could be a different issue if the standard practice is to expect terminating new path entries with a semicolon. Or, perhaps it has to do with adding new path entries to the beginning or end of the existing path string.

**Comment by NReilingh** [comment] 2016-12-21 06:07
Whoa! I spoke too soon. The issue is affecting me on this machine after all. I must have been testing without actually creating a new process session.

It seems the issue actually IS relating to the placement of the semicolon. When I reproduced the issue just now, the Install-Script cmdlet did append to the User path with a prefixed semicolon. But, when I started a new PowerShell session, this location was not in the process path DESPITE still remaining in the User path.

Once I altered the user path manually to put the semicolon in the right place, new sessions were able to successfully pick it up into the process path. I am attaching three powershell transcript files from three different powershell sessions. They demonstrate the issue as it is reproduced, identified, and manually solved. I have edited the path environment variable output in these transcripts to remove paths outside of my user directory, for security.

[1-Install_repro.txt](https://github.com/PowerShell/PowerShellGet/files/665591/1-Install_repro.txt)
[2-Demo-Manual_Modification.txt](https://github.com/PowerShell/PowerShellGet/files/665592/2-Demo-Manual_Modification.txt)
[3-Success.txt](https://github.com/PowerShell/PowerShellGet/files/665593/3-Success.txt)

**Comment by NReilingh** [comment] 2016-12-21 18:47
https://github.com/PowerShell/PowerShellGet/blob/development/PowerShellGet/PSModule.psm1#L6601

Looks like that's the problematic line.

```powershell
-Value "$currentPATHValue;$scopePath"
```
should be 
```powershell
-Value "$currentPATHValue$scopePath;"
```
or perhaps
```powershell
-Value "$scopePath;$currentPATHValue"
```

**Comment by bmanikm** [comment] 2016-12-21 20:54
@NReilingh Could you please elaborate on why ';;' in PATH value is causing the issue? Windows should ignore the empty entries in PATH value.

What is your OS?

Can you please provide the output of following commands from a new PS Console on your machine?

```powershell
# Open a new PS Console
del "$env:LOCALAPPDATA\Microsoft\Windows\PowerShell\PowerShellGet\PowerShellGetSettings.xml" -force

[System.Environment]::GetEnvironmentVariable('PATH', [System.EnvironmentVariableTarget]::Process)
[System.Environment]::GetEnvironmentVariable('PATH', [System.EnvironmentVariableTarget]::User)
[System.Environment]::GetEnvironmentVariable('PATH', [System.EnvironmentVariableTarget]::Machine)
$env:PATH

Install-Script -Verbose -Debug -Scope CurrentUser -Name $ScriptName

[System.Environment]::GetEnvironmentVariable('PATH', [System.EnvironmentVariableTarget]::Process)
[System.Environment]::GetEnvironmentVariable('PATH', [System.EnvironmentVariableTarget]::User)
[System.Environment]::GetEnvironmentVariable('PATH', [System.EnvironmentVariableTarget]::Machine)
$env:PATH

```

Now open a new PS Console and get the output of following commands.

```powershell
# Open a new PS Console
[System.Environment]::GetEnvironmentVariable('PATH', [System.EnvironmentVariableTarget]::Process)
[System.Environment]::GetEnvironmentVariable('PATH', [System.EnvironmentVariableTarget]::User)
[System.Environment]::GetEnvironmentVariable('PATH', [System.EnvironmentVariableTarget]::Machine)
$env:PATH

```

**Comment by NReilingh** [comment] 2016-12-22 02:33
@bmanikm The output of those commands is included in the transcripts I attached to my previous message.

I figured it out. The issue is that the way PSGet is currently editing the User's PATH is by [editing the registry directly with Set-ItemProperty](https://github.com/PowerShell/PowerShellGet/blob/development/PowerShellGet/PSModule.psm1#L12086). When done in this way, this updated value does not actually take effect in the current user session — new PowerShell processes will behave as though the change has not been made. Rebooting will refresh the environment from the registry, causing new powershell processes to behave as desired.

In contrast, using the `[System.Environment]::SetEnvironmentVariable()` method refreshes the environment's working memory immediately (as well as editing the registry), thereby avoiding the need to reboot. I will edit the issue title to accurately reflect this.

**Comment by bmanikm** [comment] 2016-12-22 20:58
@NReilingh, thanks for providing more details to repro this issue. 

Please note that [Environment.SetEnvironmentVariable Method (String, String, EnvironmentVariableTarget)](https://msdn.microsoft.com/en-us/library/96xafkes(v=vs.110).aspx) is not available in CoreCLR.

**Could you please run the below utility function after installing a script with your repro environment and let me know whether the issue is resolved in new PS Console without having to reboot or logoff/logon?**

```powershell

function Send-EnvironmentChangeMessage {
    # Broadcast the Environment variable changes, so that other processes pick changes to Environment variables without having to reboot or logoff/logon. 
    if (-not ('Microsoft.PowerShell.Commands.PowerShellGet.Win32.NativeMethods' -as [type])) {
        Add-Type -Namespace Microsoft.PowerShell.Commands.PowerShellGet.Win32 `
                -Name NativeMethods `
                -MemberDefinition @'
                    [DllImport("user32.dll", SetLastError = true, CharSet = CharSet.Auto)]
                    public static extern IntPtr SendMessageTimeout(
                        IntPtr hWnd,
                        uint Msg,
                        UIntPtr wParam,
                        string lParam,
                        uint fuFlags,
                        uint uTimeout,
                        out UIntPtr lpdwResult);
'@
    }

    $HWND_BROADCAST = [System.IntPtr]0xffff;
    $WM_SETTINGCHANGE = 0x1a;
    $result = [System.UIntPtr]::zero

    # https://msdn.microsoft.com/en-us/library/windows/desktop/ms644952(v=vs.85).aspx
    $returnValue = [Microsoft.PowerShell.Commands.PowerShellGet.Win32.NativeMethods]::SendMessageTimeout($HWND_BROADCAST, 
                                                                                                        $WM_SETTINGCHANGE,
                                                                                                        [System.UIntPtr]::Zero, 
                                                                                                        'Environment',
                                                                                                        2, 
                                                                                                        5000,
                                                                                                        [ref]$result);
    # A non-zero result from SendMessageTimeout indicates success.
    if($returnValue) {
        Write-Host 'Successfully broadcasted the Environment variable changes.'
    } else {
        Write-Host 'Error in broadcasting the Environment variable changes.'
    }
}

# Use this only on Windows
Send-EnvironmentChangeMessage
```

**Comment by NReilingh** [comment] 2017-01-28 02:19
@bmanikm Sorry for the long wait -- I finally got a chance to test this as I was setting up a fresh machine. It works as advertised on Windows 10 Pro!

**Closed as completed** 2017-05-11 07:44 UTC
Labels: Issue-Bug
