### ISSUE TITLE
Publish-Module traverses all of $PSModulePath when using -Path

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShellGetv2#148] opened 2017-07-12 22:21 UTC
## Steps to Reproduce (for bugs)

```powershell
Publish-Module -Path .\foo\ -Verbose 
# Verbose isn't needed it here, but it makes the repro more evident
```

## Expected Behavior

Publish should happen immediately because the exact location of the module is known. At the very least, it should be as quick as `Get-Module -ListAvailable`, as that should have all necessary information for `RequiredModules`. 

## Current Behavior

If there's a bunch of modules installed on the machine, the publish could take minutes. On the customer's machine, they were able to run `Get-Module -ListAvailable` multiple times before `Publish-Module` finished "Preparing modules for first use". 

## Possible Solution

Don't do full module analysis when the `-Path` parameter is used.

> $PSVersionTable
```
Name                           Value
----                           -----
PSVersion                      5.1.15063.313
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.413
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

> Get-Module -ListAvailable PowerShellGet,PackageManagement
```
Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     1.0.0.1    PackageManagement                   {Find-Package, Get-Package,...
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Modul...
```

> Get-PackageProvider -ListAvailable
```
Name                     Version          DynamicOptions
----                     -------          --------------
msi                      3.0.0.0          AdditionalArguments
msu                      3.0.0.0
nuget                    2.8.5.205        Destination, ExcludeVersion, Scope, SkipDep...
NuGet                    2.8.5.206        Destination, ExcludeVersion, Scope, SkipDep...
PowerShellGet            1.0.0.1          PackageManagementProvider, Type, Scope, All...
Programs                 3.0.0.0          IncludeWindowsInstaller, IncludeSystemCompo...
```

**Comment by bmanikm** [comment] 2018-07-09 20:13
This was happening due to a regression in the Test-ModuleManifest which traverses all of $PSModulePath. This issue has been resolved in the Test-ModuleManifest cmdlet.

**Closed as completed by bmanikm** 2018-07-09 20:13 UTC
Labels: Issue-Bug
