### ISSUE TITLE
Find-Command -Name doesn't support globbing

### ISSUE THREAD

**Issue by juneb** [PowerShell/PowerShellGetv2#167] opened 2017-09-17 02:01 UTC
The Name parameter of Find-Command should support globbing. Otherwise, the user has to guess or know the *exact* name of the command, or get all commands and filter the Name property.

## Expected Behavior

Find-Command -Name "*foo*" should return all commands in the gallery with names that contain "foo". Today, this returns nothing, even if the gallery contains commands that meet the criteria.

Instead, the user must guess at the exact name of the command or get all commands and filter by name, which takes up to a minute. 
(Find-Command).where{ $_.Name -like "*foo*" }
(Find-Module).AdditionalMetadata.functions -contains "*foo*"

## Repro
```
PS C:\ps-test> Find-Command -Name "*Base64*"
PS C:\ps-test>                        
PS C:\ps-test> (Find-Command).where{$_.Name -like "*Base64*"}

Name                                Version    ModuleName                          Repository
----                                -------    ----------                          ----------
ConvertFrom-Base64                  3.3.0      Pscx                                PSGallery
ConvertTo-Base64                    3.3.0      Pscx                                PSGallery
ConvertFrom-Base64                  2.5.0      Carbon                              PSGallery
ConvertTo-Base64                    2.5.0      Carbon                              PSGallery
ConvertTo-Base64                    2.2.0.2... biz.dfch.PS.System.Utilities        PSGallery
ConvertFrom-Base64                  2.2.0.2... biz.dfch.PS.System.Utilities        PSGallery
Export-Base64StringToFile           1.3.4      Avanade.CoolFunctions               PSGallery
Export-FileToBase64String           1.3.4      Avanade.CoolFunctions               PSGallery
ConvertTo-Base64                    1.0.0.0    PSPipe                              PSGallery
ConvertFrom-Base64                  1.0.0.0    PSPipe                              PSGallery
Use-CfnBase64Function               0.8.0.4    AwsCfn                              PSGallery
ConvertTo-Base64                    1.0.1.6    TAK                                 PSGallery
ConvertFrom-Base64                  1.0.1.6    TAK                                 PSGallery
Encode-ToBase64                     2.8.0      CPolydorou.General                  PSGallery
Decode-FromBase64                   2.8.0      CPolydorou.General                  PSGallery
Encode-GUIDToBase64                 2.8.0      CPolydorou.General                  PSGallery
Convert-FromBase64StringWithNoPa... 2.2        Exch-Rest                           PSGallery
Convert*-Base64String               1.0.4      Base64                              PSGallery
Add-FnBase64                        2.0.0      Vaporshell                          PSGallery
ConvertFrom-Base64                  0.6.0      PowerGRR                            PSGallery
ConvertTo-Base64                    0.6.0      PowerGRR                            PSGallery
ConvertTo-Base64URL                 1.0.6      UMN-Google                          PSGallery
Export-Base64Certificate            0.2.0      ExportBase64Certificate             PSGallery
ConvertFrom-Base64                  1.1        core                                PSGallery
ConvertTo-Base64                    1.1        core                                PSGallery
ConvertTo-Base64URL                 1.0.4      UMN-Common                          PSGallery
ConvertTo-Base64String              1.1.1      Bitbucket.v2                        PSGallery
```

**Comment by marckassay** [comment] 2019-08-07 00:47
Along at least with the Tag parameter too. My recent studies has shown this to hold true 🤓 :  
```powershell
$A = Find-Command -Tag workflow | Measure-Object
$B = Find-Command -Tag workflo* | Measure-Object
$C = Find-Command -Tag work | Measure-Object
Compare-Object -ReferenceObject $A -DifferenceObject $B -Property Count -InformationAction
Compare-Object -ReferenceObject $A -DifferenceObject $C -Property Count

Count SideIndicator
----- -------------
    0 =>
   19 <=
    0 =>
   19 <=
```

**Comment by SydneyhSmith** [comment] 2020-02-25 19:48
Closing this as a duplicate of #456 since it is the same underlying issue

**Closed as completed by SydneyhSmith** 2020-02-25 19:48 UTC
Labels: Issue-Enhancement, Up-For-Grabs
