### ISSUE TITLE
Install-Module and Update-Module errors / Unable to update PowerShellGet to fix

### ISSUE THREAD

**Issue by Dyermull** [PowerShell/PowerShellGetv2#447] opened 2019-03-18 20:18 UTC
Steps to reproduce
------------------
*The initial issue has been reported in #407, #349 and #7827 where running Install-Module and Update-Module produce errors like below.

![image](https://user-images.githubusercontent.com/48687294/54559888-11d78a00-498f-11e9-9b69-4f67e2e7abc0.png)

The cause of this issue seems to be that the expected URL for the PowerShellGallery is different from the stored repository in that there is a trailing /. 

The fix for this issue appears to be to update PowerShellGet to the latest version and this is where I am having an issue.

```powershell
Update-Module -Name PowerShellGet
```

Expected behavior
-----------------
PowerShellGet is updated
```none

```

Actual behavior
---------------
PowerShellGet was not installed by using Install-Module, so it cannot be updated

![image](https://user-images.githubusercontent.com/48687294/54560281-ff118500-498f-11e9-8b10-985ad2edac98.png)

If I run Install-Module -Name PowerShellGet -Force, I get the same error that happens whenever running Install-Module:

![image](https://user-images.githubusercontent.com/48687294/54560470-6deede00-4990-11e9-832f-392ff6f20628.png)

```none

```

Environment data
----------------
This is on Windows Server 2012 R2 that has been upgraded from WMF 4.0 to WMF 5.1.

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

```powershell
> Get-Module -ListAvailable PowerShellGet,PackageManagement
ModuleType Version    Name
---------- -------    ----
Binary     1.0.0.1    PackageManagement
Script     1.0.0.1    PowerShellGet
```

```powershell
> Get-PackageProvider -ListAvailable
msi                      3.0.0.0
msu                      3.0.0.0
NuGet                    2.8.5.208
PowerShellGet            1.0.0.1
Programs                 3.0.0.0
```

**Comment by SydneyhSmith** [comment] 2019-03-18 22:07
@Dyermull thanks for opening the issue, we are investigating, might be related to Windows Server 2012 R2

**Comment by SydneyhSmith** [comment] 2019-03-18 22:11
Could you also provide us with ```Get-PSRepsitory```and ```Get-Module PowerShellGet -listavailable```? 
A work around you may also want to try in uninstalling PowerShellGet and then re-installing it

**Comment by edyoung** [comment] 2019-03-19 03:41
I don't think this is related to #407 etc. Those are to do with Update-Module specifically. If you have a problem with Install-Module it is different. You may have some sort of connectivity problem, but it's odd because you must have contacted the gallery in order to find that PowerShellGet has PackageManagement as a dependency. Please try:

```powershell
Install-Module PowerShellGet -Force -AllowClobber -Debug -Verbose
```
and share the output.

**Comment by Dyermull** [comment] 2019-03-19 14:31
@SydneyhSmith  Thanks, here are the results from the commands.
**Get-PSRepository**
Name                      InstallationPolicy   SourceLocation
PSGallery                 Trusted                  https://www.powershellgallery.com/api/v2


**Get-Module PowerShellGet -listavailable**

    Directory: C:\Program Files\WindowsPowerShell\Modules
ModuleType Version    Name                                ExportedCommands
Script            1.0.0.1      PowerShellGet                  {Install-Module, Find-Module, Save-Module, Updat...

**Comment by Dyermull** [comment] 2019-03-19 14:37
@edyoung Thank you for looking into this too. Here are the results from the command requested.

PS C:\Users\app_admin> Install-Module PowerShellGet -Force -AllowClobber -Debug -Verbose
DEBUG: 00:00:00.0000011 Calling New() : MethodName = 'GetDynamicOptions'

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: 00:00:00.0000384 Force: True
DEBUG: 00:00:00.0000576 Debug: True
DEBUG: 00:00:00.0000815 Name: PowerShellGet
DEBUG: 00:00:00.0001002 Verbose: True
DEBUG: 00:00:00.0008717 INVOKING PowerShell Fn Get-DynamicOptions with args Provider that has length 1
DEBUG: 00:00:00.0017917 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0035642 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0093916 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0094237 Force: True
DEBUG: 00:00:00.0094494 Debug: True
DEBUG: 00:00:00.0094676 Name: PowerShellGet
DEBUG: 00:00:00.0094850 Verbose: True
DEBUG: 00:00:00.0101982 INVOKING PowerShell Fn Get-DynamicOptions with args Source that has length 1
DEBUG: 00:00:00.0108969 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0133351 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0190611 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0191031 Force: True
DEBUG: 00:00:00.0191335 Debug: True
DEBUG: 00:00:00.0191610 Name: PowerShellGet
DEBUG: 00:00:00.0191891 Verbose: True
DEBUG: 00:00:00.0200873 INVOKING PowerShell Fn Get-DynamicOptions with args Package that has length 1
DEBUG: 00:00:00.0206575 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0315610 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0376576 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0377015 Force: True
DEBUG: 00:00:00.0377274 Debug: True
DEBUG: 00:00:00.0377529 Name: PowerShellGet
DEBUG: 00:00:00.0377772 Verbose: True
DEBUG: 00:00:00.0386669 INVOKING PowerShell Fn Get-DynamicOptions with args Install that has length 1
DEBUG: 00:00:00.0394921 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0435007 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:11.2161812 Calling SearchForPackages. Name='PowerShellGet'
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
DEBUG: 00:00:11.2173176 PackageProvider::FindPackage with name PowerShellGet
DEBUG: 00:00:11.2179706 Calling SearchForPackages After Select 1
DEBUG: 00:00:11.2249748 Calling New() : MethodName = 'FindPackage'
DEBUG: 00:00:11.2267467 ProviderName: PowerShellGet
DEBUG: 00:00:11.2282369 Type: Module
DEBUG: 00:00:11.2296907 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:11.2310595 AllowClobber: True
DEBUG: 00:00:11.2322720 Force: True
DEBUG: 00:00:11.2335896 Debug: True
DEBUG: 00:00:11.2349417 Scope: AllUsers
DEBUG: 00:00:11.2364896 Verbose: True
DEBUG: 00:00:11.2377721 Name: PowerShellGet
DEBUG: 00:00:11.2398769 INVOKING PowerShell Fn Find-Package with args System.String[], , ,  that has length 4
DEBUG: 00:00:11.2464542 In PowerShellGet Provider - 'Find-Package'.
DEBUG: 00:00:11.2482166 OPTION: ProviderName => PowerShellGet
DEBUG: 00:00:11.2502612 OPTION: Type => Module
DEBUG: 00:00:11.2519884 OPTION: MessageResolver =>
Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:11.2544567 OPTION: AllowClobber => True
DEBUG: 00:00:11.2862344 OPTION: Force => True
DEBUG: 00:00:11.3883397 OPTION: Debug => True
DEBUG: 00:00:11.3899918 OPTION: Scope => AllUsers
DEBUG: 00:00:11.3915769 OPTION: Verbose => True
DEBUG: 00:00:11.3937581 OPTION: Name => PowerShellGet
VERBOSE: The -Repository parameter was not specified.  PowerShellGet will use all of the registered
repositories.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider
is 'NuGet'.
DEBUG: 00:00:11.4937166 PackageProvider::FindPackage with name PowerShellGet
DEBUG: 00:00:11.5491464 Calling 'NuGet'::'FindPackage' - name='PowerShellGet',
requiredVersion='',minimumVersion='', maximumVersion='''.
DEBUG: 00:00:11.6956268 Iterating 'PowerShellGet'.
DEBUG: 00:00:11.7418957 There are '0' registered sources in 'NuGet' provider.
DEBUG: 00:00:11.7443070 Source 'https://www.powershellgallery.com/api/v2' is not one of the registered
sources in 'NuGet' provider.
DEBUG: 00:00:12.3655250 Source 'https://www.powershellgallery.com/api/v2' is validated.
DEBUG: 00:00:12.3683687 Calling 'NuGetRequest'::'GetPackageById', 'PowerShellGet'.
DEBUG: 00:00:12.4673626 Calling 'HttpClientPackageRepository'::'FindPackagesById', 'PowerShellGet'.
DEBUG: 00:00:12.4698970 Calling 'NuGetClient'::'FindPackage'.
VERBOSE: Searching repository
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PowerShellGet'' for ''.
DEBUG: 00:00:12.4755122 Downloading
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PowerShellGet'&$skip=0&$top=40'.
DEBUG: 00:00:12.6394474 Completed downloading
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PowerShellGet'&$skip=0&$top=40'.
DEBUG: 00:00:12.6497240 '18' packages received in the last request.
VERBOSE: Total package yield:'1' for the specified package 'PowerShellGet'.
DEBUG: 00:00:12.6626201 Completed iterating for 'PowerShellGet'.
DEBUG: 00:00:12.9175262 Done calling powershell «Find-Package» «PSModule»
DEBUG: 00:00:13.0118450 Calling New() : MethodName = 'GetInstalledPackages'
DEBUG: 00:00:13.0177405 ProviderName: PowerShellGet
DEBUG: 00:00:13.0193245 Type: Module
DEBUG: 00:00:13.0205658 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:13.0763516 AllowClobber: True
DEBUG: 00:00:13.0818544 Force: True
DEBUG: 00:00:13.0838635 Debug: True
DEBUG: 00:00:13.0890231 Scope: AllUsers
DEBUG: 00:00:13.0905020 Verbose: True
DEBUG: 00:00:13.0917585 Name: PowerShellGet
DEBUG: 00:00:13.1006968 INVOKING PowerShell Fn Get-InstalledPackage with args PowerShellGet, 2.1.2, ,  that
has length 4
DEBUG: 00:00:13.1111615 In PowerShellGet Provider - 'Get-InstalledPackage'.
DEBUG: 00:00:13.1128535 OPTION: ProviderName => PowerShellGet
DEBUG: 00:00:13.1143986 OPTION: Type => Module
DEBUG: 00:00:13.1169580 OPTION: MessageResolver =>
Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:13.1206522 OPTION: AllowClobber => True
DEBUG: 00:00:13.1222460 OPTION: Force => True
DEBUG: 00:00:13.1238162 OPTION: Debug => True
DEBUG: 00:00:13.1252367 OPTION: Scope => AllUsers
DEBUG: 00:00:13.1268033 OPTION: Verbose => True
DEBUG: 00:00:13.1283378 OPTION: Name => PowerShellGet
DEBUG: 00:00:13.1520983 PowerShell Script 'PSModule' Function 'Get-InstalledPackage' returns null.
DEBUG: 00:00:13.1810095 Done calling powershell «Get-InstalledPackage» «PSModule»

Confirm
Are you sure you want to perform this action?
Performing the operation "Install-Module" on target "Version '2.1.2' of module 'PowerShellGet'".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: 00:00:22.7602777 Calling New() : MethodName = 'InstallPackage'
DEBUG: 00:00:22.7630189 ProviderName: PowerShellGet
DEBUG: 00:00:22.7661729 Type: Module
DEBUG: 00:00:22.7684853 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:22.7727869 AllowClobber: True
DEBUG: 00:00:22.7761910 Force: True
DEBUG: 00:00:22.7777491 Debug: True
DEBUG: 00:00:22.7805339 Scope: AllUsers
DEBUG: 00:00:22.7823425 Verbose: True
DEBUG: 00:00:22.7844870 Name: PowerShellGet
DEBUG: 00:00:22.7861230 INVOKING PowerShell Fn Install-Package with args
NuGet|PowerShellGet|2.1.2|https://www.powershellgallery.com/api/v2|Module that has length 1
DEBUG: 00:00:22.7898580 In PowerShellGet Provider - 'Install-Package'.
DEBUG: 00:00:22.7917583 In PowerShellGet Provider - 'Install-PackageUtility'.
DEBUG: 00:00:22.7935600 The FastPackageReference is
'NuGet|PowerShellGet|2.1.2|https://www.powershellgallery.com/api/v2|Module'.
DEBUG: 00:00:22.7959288 OPTION: ProviderName => PowerShellGet
DEBUG: 00:00:22.7975050 OPTION: Type => Module
DEBUG: 00:00:22.7992373 OPTION: MessageResolver =>
Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:22.8025068 OPTION: AllowClobber => True
DEBUG: 00:00:22.8045194 OPTION: Force => True
DEBUG: 00:00:22.8065066 OPTION: Debug => True
DEBUG: 00:00:22.8092932 OPTION: Scope => AllUsers
DEBUG: 00:00:22.8118612 OPTION: Verbose => True
DEBUG: 00:00:22.8139601 OPTION: Name => PowerShellGet
VERBOSE: The installation scope is specified to be 'AllUsers'.
VERBOSE: The specified module will be installed in 'C:\Program Files\WindowsPowerShell\Modules'.
DEBUG: 00:00:22.8216398 ArtfactType is Module
VERBOSE: The specified Location is 'NuGet' and PackageManagementProvider is 'NuGet'.
VERBOSE: Downloading module 'PowerShellGet' with version '2.1.2' from the repository
'https://www.powershellgallery.com/api/v2'.
DEBUG: 00:00:22.9033387 Calling 'NuGet'::'InstallPackage',
'$aHR0cHM6Ly93d3cucG93ZXJzaGVsbGdhbGxlcnkuY29tL2FwaS92Mg==\UG93ZXJTaGVsbEdldA==\Mi4xLjI=\aHR0cHM6Ly93d3cucG93
ZXJzaGVsbGdhbGxlcnkuY29tL2FwaS92Mg==\cG93ZXJzaGVsbGdldA=='.
DEBUG: 00:00:22.9064262 Calling 'NuGetRequest'::'GetPackageByFastpath',
'$aHR0cHM6Ly93d3cucG93ZXJzaGVsbGdhbGxlcnkuY29tL2FwaS92Mg==\UG93ZXJTaGVsbEdldA==\Mi4xLjI=\aHR0cHM6Ly93d3cucG93
ZXJzaGVsbGdhbGxlcnkuY29tL2FwaS92Mg==\cG93ZXJzaGVsbGdldA=='.
DEBUG: 00:00:22.9099683 Calling 'NuGetRequest'::'ResolvePackageSource',
'https://www.powershellgallery.com/api/v2'.
DEBUG: 00:00:22.9124557 Calling 'NuGetRequest'::'FindRegisteredSource',
'https://www.powershellgallery.com/api/v2'.
DEBUG: 00:00:22.9148391 Source 'https://www.powershellgallery.com/api/v2' is not one of the registered
sources in 'NuGet' provider.
DEBUG: 00:00:23.2499730 Calling 'HttpClientPackageRepository'::'FindPackage', 'PowerShellGet'.
DEBUG: 00:00:23.2524035 Calling 'NuGetClient'::'FindPackage'.
VERBOSE: Searching repository
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PowerShellGet'' for ''.
DEBUG: 00:00:23.2584930 Downloading
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PowerShellGet'&$skip=0&$top=40'.
DEBUG: 00:00:23.4598557 Completed downloading
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PowerShellGet'&$skip=0&$top=40'.
DEBUG: 00:00:23.4637043 '18' packages received in the last request.
DEBUG: 00:00:23.4657982 'Package version' is '2.1.2'.
DEBUG: 00:00:23.4674385 'Request's Destination' is 'C:\Users\app_admin\AppData\Local\Temp\2\3732685'.
DEBUG: 00:00:23.4690861 Calling 'NuGetClient'::'GetPackageDependencies'.
DEBUG: 00:00:23.4707559 There are '0' registered sources in 'NuGet' provider.
DEBUG: 00:00:23.4731013 Source 'https://www.powershellgallery.com/api/v2' is not one of the registered
sources in 'NuGet' provider.
DEBUG: 00:00:23.5665495 Source 'https://www.powershellgallery.com/api/v2' is validated.
DEBUG: 00:00:23.5696069 Calling 'NuGetRequest'::'GetPackageById', 'PackageManagement'.
DEBUG: 00:00:23.6628285 Calling 'HttpClientPackageRepository'::'FindPackagesById', 'PackageManagement'.
DEBUG: 00:00:23.6647353 Calling 'NuGetClient'::'FindPackage'.
VERBOSE: Searching repository
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PackageManagement'' for ''.
DEBUG: 00:00:23.6684965 Downloading
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PackageManagement'&$skip=0&$top=40'.
DEBUG: 00:00:23.7177836 Completed downloading
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PackageManagement'&$skip=0&$top=40'.
DEBUG: 00:00:23.7203747 '14' packages received in the last request.
DEBUG: 00:00:23.7227192 Returning the call 'NuGetClient'::'GetPackageDependencies'.
DEBUG: 00:00:23.7691683 Calling 'NuGetClient'::'InstallPackage'.
VERBOSE: InstallPackage' - name='PackageManagement',
version='1.3.1',destination='C:\Users\app_admin\AppData\Local\Temp\2\3732685'
VERBOSE: DownloadPackage' - name='PackageManagement',
version='1.3.1',destination='C:\Users\app_admin\AppData\Local\Temp\2\3732685\PackageManagement\PackageMana
gement.nupkg', uri='https://www.powershellgallery.com/api/v2/package/PackageManagement/1.3.1'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/PackageManagement/1.3.1'.
VERBOSE: An error occurred while sending the request.
DEBUG: 00:00:24.2226303    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PackageManagement.NuGetProvider.NuGetClient.<DownloadDataToFileAsync>d__15.MoveNext()
VERBOSE: Retry downloading 'https://www.powershellgallery.com/api/v2/package/PackageManagement/1.3.1' for '2'
 more times
VERBOSE: An error occurred while sending the request.
DEBUG: 00:00:24.3943537    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PackageManagement.NuGetProvider.NuGetClient.<DownloadDataToFileAsync>d__15.MoveNext()
VERBOSE: Retry downloading 'https://www.powershellgallery.com/api/v2/package/PackageManagement/1.3.1' for '1'
 more times
VERBOSE: An error occurred while sending the request.
DEBUG: 00:00:24.5644314    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PackageManagement.NuGetProvider.NuGetClient.<DownloadDataToFileAsync>d__15.MoveNext()
VERBOSE: Retry downloading 'https://www.powershellgallery.com/api/v2/package/PackageManagement/1.3.1' for '0'
 more times
VERBOSE: Downloading package 'PackageManagement' failed, please make sure
'https://www.powershellgallery.com/api/v2/package/PackageManagement/1.3.1' is accessable.
WARNING: Source Location 'https://www.powershellgallery.com/api/v2/package/PackageManagement/1.3.1' is not
valid.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
PS C:\Users\app_admin>

**Comment by edyoung** [comment] 2019-03-19 19:56
That's pretty odd. can you try invoke-webrequest "https://www.powershellgallery.com/api/v2/package/PackageManagement/1.3.1" ? That should produce an error which will hopefully indicate why you can't download the package

**Comment by Dyermull** [comment] 2019-03-19 21:38
That is interesting.

invoke-webrequest : The underlying connection was closed: Could not establish trust relationship for the
SSL/TLS secure channel.
At line:1 char:1
+ invoke-webrequest "https://www.powershellgallery.com/api/v2/package/P ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebReques
   t], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCo
   mmand

**Comment by alerickson** [comment] 2019-03-19 21:42
I've encountered an error with Windows Server 2008 where I couldn't install/update Package Management.  I needed to manually delete dlls under the top level folder (C:\Program Files\WindowsPowerShell\Modules\PackageManagement\) and restart powershell.

**Comment by edyoung** [comment] 2019-03-20 00:00
@alerickson I think that's different from @dyermull's case.

Do you have a web proxy? Does invoke-webrequest https://www.powershellgallery.com/ work?

**Comment by Dyermull** [comment] 2019-03-20 00:37
We do not have a web proxy. invoke-webrequest https://www.powershellgallery.com/ seems to work. It returns a Status Code of 200 and Description of OK and a lot of other information. I will post if it is relevant.

Just to give a little more information. This is happening on all (4) servers (2012 R2) that I have tested. On at least two of them the Install-Module and Update-Module worked fairly recently. The one that I'm running all these tests on is a Dev server, however it is broken on production servers too. I am able to run these commands on Windows 10 laptops and VMs without an issue from the same network.

I ran the invoke-webrequest "https://www.powershellgallery.com/api/v2/package/PackageManagement/1.3.1" and checked the Windows error logs and noticed something interesting. There is a cert error, posted below:

An operation failed because the following certificate has validation errors:

Subject Name: CN=psg-prod-eastus.azureedge.net, O="OpenDNS, Inc.", L=San Francisco, S=California, C=US
Issuer Name: O=Cisco, CN=Cisco Umbrella Secondary SubCA ash-SG
Thumbprint: (Removed - not sure if it matters or not)

Errors:

 PartialChain: A certificate chain could not be built to a trusted root authority.
RevocationStatusUnknown: The revocation function was unable to check revocation for the certificate.
OfflineRevocation: The revocation function was unable to check revocation because the revocation server was offline.
.

This error does not appear on every server that is having the problem, including the production one that I need to get working, so I'm not sure if it truly is a cert issue or not.

Thanks for the help!

**Comment by edyoung** [comment] 2019-03-20 05:22
Thanks, that helps a lot. It would appear that the certificate which is being used by the CDN service (psg-prod-eastus.azureeedge.net is our CDN) is not trusted because you can't reach the revocation server to check the CRL. 

Try going to https://psg-prod.eastus.azureedge.net/ using a browser and look at the cert details (by clicking on the lock next to the URL - exact steps depend on browser).

I see:
*.vo.msecnd.net (CRL http://mscrl.microsoft.com/pki/mscorp/crl/Microsoft%20IT%20TLS%20CA%202.crl)
Microsoft IT TLS CA 2 (CRL http://crl3.digicert.com/Omniroot2025.crl) 
Baltimore CyberTrust Root (root CA, no CRL and should be pre-trusted in the OS).

Which is a little different than what you see. I don't know why the CDN might use different certs for different points of presence but it's not necessarily wrong. If you can look at the cert, it has a property which is the revocation list (CRL). You should be able to reach that the CRL URL - you could check it with invoke-webrequest <that url>. The error message above suggests that it can't be reached. If we can identify the cert and CRL I can raise the issue with the CDN and get them to fix it.

As a potential workaround for this you could install packagemanagement and powershellget by downloading it manually from the gallery via a browser (go to https://www.powershellgallery.com/packages/PackageManagement/1.3.1 and follow the 'manual download' steps, same for powershellget).

**Comment by Dyermull** [comment] 2019-03-20 21:00
I tried going to https://psg-prod.eastus.azureedge.net/ but wasn't able to get there from the server. Tried on my laptop and a VM, both gave a "Server IP address could not be found". I had a friend in another organization try it and he got the same thing. We both noticed that the browser quit trying really fast - as in it didn't take more than a couple seconds to get the following message using Chrome:

This site can’t be reached psg-prod.eastus.azureedge.net’s server IP address could not be found.
Try running Windows Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN

As far as the work-around goes, I'm game to try it, I just wanted to make sure I wasn't missing a cleaner fix. I've read the Manual Download documentation, but didn't see what to do with the existing module files and folders. Should I delete them first? Is there a best way to do this other than just deleting them -like a PS command to delete/clean them up?

Thanks again.

**Comment by edyoung** [comment] 2019-03-21 00:42
Sorry! it's psg-prod-eastus, not psg-prod.eastus. typo on my part :-|

**Comment by Dyermull** [comment] 2019-03-21 16:44
I'm using the following link for my tests: https://psg-prod-eastus.azureedge.net/

I tried the new link with various results depending on the machine and browser. On the 2012 R2 server, Internet Explorer will not load the page or cert - just the standard "There is a problem with this website's security certificate." "The security certificate presented by this website was not issued by a trusted certificate authority." 

If I click "Continue to this website" it just seems to refresh and bring me back to the same page no matter how many times I click.

Using Chrome on the same server, I get the warning - "This server could not prove that it is psg-prod-eastus.azureedge.net; its security certificate is not trusted by your computer's operating system. This may be caused by a misconfiguration or an attacker intercepting your connection." 

If I then click on "Proceed to psg-prod-eastus.azureedge.net (unsafe)" it just keeps looping me back to the 1st Chrome warning page and does not advance.

IE on a laptop running Windows 10 just gives a 400 error. Chrome on the same laptop does seem to load the page with an Invalid Query Parameter Value message. The cert details from the laptop (which doesn't have the PowerShell issue) are not close to yours and I think we're talking Certification Path? because the Details page of the cert really doesn't look like yours. Would it help to post that info?

**Comment by Dyermull** [comment] 2019-03-21 18:42
Below is a screenshot of that URL's Certification Path. 

![image](https://user-images.githubusercontent.com/48687294/54776789-d29f7800-4bde-11e9-821a-4b754ca0be3b.png)

I looked through each of the certs in the chain and the only one with CRL info in its properties is the 2nd one, "Cisco Umbrella Primary SubCA" The url under CRL Distribution Point is: 

http://www.cisco.com/security/pki/crl/ciscoumbrellaroot.crl

![image](https://user-images.githubusercontent.com/48687294/54776844-f1057380-4bde-11e9-8ca7-0ce5c71c5243.png)

Not sure if this helps or not since it's not on the server I am having issues with, just trying to give as much info as I can.

**Comment by Dyermull** [comment] 2019-03-21 18:46
Also, I can download that CRL file from the server, but running an Invoke-Webrequest http://www.cisco.com/security/pki/crl produces an error: "The request was aborted: Could not create SSL/TLS secure channel."

**Comment by edyoung** [comment] 2019-03-21 20:51
I believe your company is using Cisco umbrella to man-in-the-middle the traffic. That is, they intercept all the traffic and use a special root CA which should be installed on all the client machines to reassure the client that that this is ok. (this is not super unusual btw). That's why the cert you see is not the same as the one our CDN actually uses.

But something is wrong - either with cert distribution (maybe the machine which is having trouble doesn't have the root cert installed) or CRL access. This isn't something we can do much about - please contact your network administrator to work out what the issue is.

**Comment by J3bs** [comment] 2019-03-26 15:28
I've run into this before, and in my case it was caused by SSL/TLS version compatibility, for whatever reason powershell was not obeying our policy to enforce TLS1.2 + and was trying to use SSLv3.

Verify current TLS support of your powershell: `[Net.ServicePointManager]::SecurityProtocol`

Response MUST include either "TLS10", "TLS11", or "TLS12"

Change to TLS1.2: `[Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;`

**Comment by Dyermull** [comment] 2019-03-26 16:02
Thanks, the response I get is: ```PS C:\Windows\system32> [Net.ServicePointManager]::SecurityProtocol
Ssl3, Tls ```

Changing to TLS1.2 was successful, but didn't fix the issue. I was getting the same errors. I rebooted and PS had reverted to Ssl3 and Tls. Found out through some more testing that just closing and re-opening PS would cause the setting to revert to Ssl3, Tls after setting it to TLS1.2. Shouldn't that be persistent?

**Comment by edyoung** [comment] 2019-03-27 04:29
The setting is not persistent. See https://docs.microsoft.com/en-us/security/solving-tls1-problem#update-windows-powershell-scripts-or-related-registry-settings for details on how to persistently change it; but since it doesn't sound like it solves the issue, my advice is still to find the person who configured the Cisco umbrella product for your company

**Comment by Dyermull** [comment] 2019-03-27 16:12
@edyoung Thanks, I'll continue to work with our Network team on this issue and post once we make some progress.

**Comment by Dyermull** [comment] 2019-03-29 20:56
Think I have a general idea of what is causing the problem, but not precisely. I worked with our Network team and after much testing on a pair of dev servers, we got one to work, where it turned out all it needed was to have the Cisco Umbrella Root CA installed. Everything worked after that. However, this was a pretty bare-bones server without much customization. The servers that I wanted to install modules on still wouldn't run install-module/update-module no matter what we tried and I was getting inconsistent results across my set of test machines.

I discovered the difference on the servers that wouldn't work is that they are SharePoint servers and I was using the SharePoint 2013 Management Shell for PowerShell (like I have for years on everything PowerShell.) This management shell runs a PS script at launch with the main command:
```Add-PSSnapin Microsoft.SharePoint.PowerShell```

For reasons still unclear to me, Install-Module will not work if that PSSnapin is loaded. I tried running base Windows PowerShell and Install-Module works fine (Cisco cert loaded too, of course). As soon as I ran the command to load the SharePoint snapin, Install-Module broke, with the same errors as before. I tested this work-around on three servers with the same results. Success.

I don't know if the question of what the SharePoint snapin is loading/doing that is affecting the PowerShellGet modules belongs here or not, but if anyone has any idea why that might be happening and if there's a fix, I'd love to hear it. If not and this should be closed or moved to another area, please let me know.

Thanks for all the advice.

**Comment by johnorotisimo** [comment] 2019-04-02 19:48
I installed the Cisco Root Certificate Authority to the computer root cert store. I got it from the Deployments/Configuration/Root Certificate location from the clients MSP Dashboard.
I was able to use the Install-Module command directly from the ISE after that.

From the DL page:
Umbrella's Block Page feature presents an SSL certificate to browsers that make connections to blocked sites. The certificate will match the requested site but will be signed by the Cisco Root Certificate Authority (CA).

**Comment by edyoung** [comment] 2019-04-07 15:45
@Dyermull, sorry to hear you're still seeing some issues. I think the cisco issue is out of scope for us. Regarding SharePoint snapin, it's quite odd that it affects Install-Module. I think that's an issue for the SharePoint team, probably best reported via https://sharepoint.uservoice.com/forums/330318-sharepoint-administration . I'm going to close this because I don't think there's something we can fix in PowerShellGet.

**Closed as completed by edyoung** 2019-04-07 15:45 UTC
Labels: Issue-Bug, Install-Module, Update-Module
