### ISSUE TITLE
Save/Install-Package cmdlets not able to install packages in Linux or MacOS 

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShellGetv2#286] opened 2018-05-24 20:32 UTC
I've been seen this for sometime with one particular package:
```
Microsoft.SqlServer.SqlManagementObjects
```
But, just to find our that it wasn't only one package.

## Expected Behavior

To install the package successfully.

## Current Behavior

It can't install due to missing dependencies:
```
install-package : Unable to find dependent package(s) (System.Reflection.Emit.Lightweight)
At line:1 char:1
+ install-package -Name Microsoft.SqlServer.SqlManagementObjects -force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (System.Reflection.Emit.Lightweight:String) [Install-Package], Exception
+ FullyQualifiedErrorId : UnableToFindDependencyPackage,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

## Possible Solution

I could not find a workaround as I can't even use the Save-Package cmdlet
```
PS /home/maxt> save-package -Name Microsoft.SqlServer.SqlManagementObjects -path /home/maxt/Downloads                   
WARNING: Unable to find dependent package(s) (System.Reflection.Emit.Lightweight)
WARNING: Unable to find dependent package(s) (System.Reflection.Emit)
WARNING: Unable to find dependent package(s) (System.Xml.XDocument)
WARNING: Unable to find dependent package(s) (System.Threading.Timer)
WARNING: Unable to find dependent package(s) (System.Threading.Thread)
WARNING: Unable to find dependent package(s) (runtime.native.System.Data.SqlClient.sni)
save-package : Unable to save the package 'Microsoft.SqlServer.SqlManagementObjects.140.17265.0.nupkg'.
At line:1 char:1
+ save-package -Name Microsoft.SqlServer.SqlManagementObjects -path /ho ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Microsoft.Power...ets.SavePackage:SavePackage) [Save-Package], Exception
+ FullyQualifiedErrorId : ProviderFailToDownloadFile,Microsoft.PowerShell.PackageManagement.Cmdlets.SavePackage
```

## Steps to Reproduce (for bugs)

Try to install the following packages in Linux:

- Microsoft.SqlServer.SqlManagementObjects
- NETStandard.Library

1. sudo pwsh
2. install-package -Name Microsoft.SqlServer.SqlManagementObjects -force
3. install-package -Name NETStandard.Library -force

Installation error on both packages:
```
install-package : Unable to find dependent package(s) (System.Reflection.Emit.Lightweight)
```

## Your Environment
Linux
```
[maxt@mercury ~]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

```PowerShell
PS /home/maxt> $PSVersionTable                                                                                          

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.2
PSEdition                      Core
GitCommitId                    v6.1.0-preview.2
OS                             Linux 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS /home/maxt> Get-Module                                                                                               

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemPropert...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     1.1.7.2    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-Pack...
Script     1.6.5      PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCap...
Script     1.2        PSReadLine                          {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remove-PS...

PS /home/maxt> Get-Module -ListAvailable PowerShellGet,PackageManagement                                                


    Directory: /usr/local/share/powershell/Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.1.7.2    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-Packa...
Script     1.6.5      PowerShellGet                       {Find-Command, Find-DSCResource, Find-Module, Find-RoleCap...


    Directory: /opt/microsoft/powershell/6.1.0~preview.2/Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.1.7.0    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-Packa...

PS /home/maxt> Get-PackageProvider                                                                                      

Name                     Version          DynamicOptions
----                     -------          --------------
NuGet                    2.8.5.210        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag...
PowerShellGet            1.6.5.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, ...

PS /home/maxt> Get-PackageProvider -ListAvailable                                                                       

Name                     Version          DynamicOptions
----                     -------          --------------
NuGet                    2.8.5.210        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag...
PowerShellGet            1.6.5.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, ...
```
![powershellget_pkgissue_2018-05-24_16-21-07](https://user-images.githubusercontent.com/19892435/40512146-db27987e-5f6f-11e8-803c-33c1d16e04f6.jpg)

**Comment by MaximoTrinidad** [comment] 2018-05-24 20:44
@SteveL-MSFT / @joeyaiello 

I'm tagging you both just in case PowerShell Core has to do with this issue to.
I have no issues with Windows!

:)

**Comment by bmanikm** [comment] 2018-05-24 23:04
This is a duplicate of https://github.com/OneGet/oneget/issues/322.

It looks like all the versions of System.Reflection.Emit.Lightweight  and System.Reflection.Emit packages got unlisted on NuGet.org.

```PowerShell
PS C:\> Find-Package -ProviderName NuGet -Source https://nuget.org/api/v2 -AllowPrereleaseVersions System.Reflection.Emit.Lightweight
Find-Package : No match was found for the specified search criteria and package name 'System.Reflection.Emit.Lightweight'. Try Get-PackageSource to see all available registered package sources.
At line:1 char:1
+ Find-Package -ProviderName NuGet -Source https://nuget.org/api/v2 -Al ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...ets.FindPackage:FindPackage) [Find-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.FindPackage

PS C:\> Find-Package -ProviderName NuGet -Source https://nuget.org/api/v2 -AllowPrereleaseVersions System.Reflection.Emit
Find-Package : No match was found for the specified search criteria and package name 'System.Reflection.Emit'. Try Get-PackageSource to see all available registered package sources.
At line:1 char:1
+ Find-Package -ProviderName NuGet -Source https://nuget.org/api/v2 -Al ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...ets.FindPackage:FindPackage) [Find-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.FindPackage

PS C:\>
PS C:\> Find-Package -ProviderName NuGet -Source https://nuget.org/api/v2 -AllowPrereleaseVersions System.Reflection.Emit.Lightweight -RequiredVersion 4.3.0

Name                           Version          Source                           Summary
----                           -------          ------                           -------
System.Reflection.Emit.Ligh... 4.3.0            https://nuget.org/api/v2         Provides the System.Reflection.Emit.DynamicMethod class, which represents a dynamic method that can be compiled, executed, and


PS C:\> Find-Package -ProviderName NuGet -Source https://nuget.org/api/v2 -AllowPrereleaseVersions System.Reflection.Emit -RequiredVersion 4.3.0

Name                           Version          Source                           Summary
----                           -------          ------                           -------
System.Reflection.Emit         4.3.0            https://nuget.org/api/v2         Provides classes that allow a compiler or tool to emit metadata and optionally generate a PE file on disk. The primary clients
```

**Comment by bmanikm** [comment] 2018-05-24 23:06
This issue was moved to OneGet/oneget#361

**Closed as completed by bmanikm** 2018-05-24 23:06 UTC
