### ISSUE TITLE
Publish-Module should work in Core edition

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShellGetv2#26] opened 2016-10-17 16:03 UTC
_From @vors on August 6, 2016 23:42_

I developed module [MarkdownLinkCheck](https://github.com/vors/MarkdownLinkCheck) fully on OS X. To my great surprise, I didn't encounter any cross-platform problems when I tested the result on inbox Windows PS version. 
It's particularly remarkable, because there is a binary part (netstandard assembly) in the package, but it works fine on full framework.

Today I tried to publish the module to PSGallery and it turns out to be **the only place** in the whole development cycle that required me to hop back to a windows machine.

Here is the result that I got on OS X:

```
PS /Users/vors/dev/MarkdownLinkCheck> Publish-Module -Name MarkdownLinkCheck -Verbose -RequiredVersion 0.1.0                                 
Publish-Module : Publish-Module is not supported on Nano Server and PowerShellCore.
At line:1 char:1
+ Publish-Module -Name MarkdownLinkCheck -Verbose -RequiredVersion 0.1. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Manageme....PSScriptCmdlet:PSScriptCmdlet) [Publish-Module], InvalidOperationExcept 
   ion
    + FullyQualifiedErrorId : PublishModuleIsNotSupportedOnNanoServer,Publish-Module
```

cc @raghushantha @quoctruong @KrishnaV-MSFT 

_Copied from original issue: PowerShell/PowerShell#1673_

**Comment by SteveL-MSFT** [comment] 2016-10-17 16:03
_From @raghushantha on August 8, 2016 18:51_
- @bmanikm 

@vors Publish-Module is written on top of Nuget.exe which works on FullCLR only.
https://github.com/PowerShell/PowerShell/issues/1294

Created a new feature task to track the porting work. Will be a post Aug 17 item:
https://github.com/PowerShell/PowerShell/issues/1678

**Comment by bmanikm** [comment] 2016-10-17 18:17
This is a duplicate of #25

**Closed as completed by bmanikm** 2016-10-17 18:17 UTC
